# -- Site Configuration --
theme = "congo"
baseURL = "https://niche-finance-blog.vercel.app/"
title = "SmartStack: AI, Self-Hosting & Smart Finance"
defaultContentLanguage = "en"
disableLanguages = ["de", "es", "ja", "zh-Hans"]

enableRobotsTXT = true
summaryLength = 30
hasCJKLanguage = true

buildDrafts = false
buildFuture = false

enableEmoji = true

[pagination]
  pagerSize = 10

[taxonomies]
  tag = "tags"
  category = "categories"
  author = "authors"
  series = "series"

[outputs]
  home = ["HTML", "RSS", "JSON"]
