# -- Main Menu --
# The main menu is displayed in the header at the top of the page.

[[main]]
  name = "Self-Hosting"
  url = "/tags/selfhosted/"
  weight = 10

[[main]]
  name = "AI & Automation"
  url = "/tags/technology/"
  weight = 20

[[main]]
  name = "Smart Finance"
  url = "/tags/finance/"
  weight = 30

[[main]]
  name = "GitHub"
  url = "https://github.com/soiieking/niche-finance-blog"
  weight = 40
  [main.params]
    icon = "github"
    showName = false
    target = "_blank"

[[main]]
  identifier = "search"
  weight = 99
  [main.params]
    action = "search"

[[main]]
  identifier = "locale"
  weight = 100
  [main.params]
    action = "locale"
