baseURL = 'https://niche-finance-blog.vercel.app/'
languageCode = 'en-us'
title = 'SmartStack: AI, Self-Hosting & Smart Finance'
theme = 'hugo-PaperMod'

[params]
    defaultTheme = "auto"
    showShareButtons = true
    showReadingTime = true

    # Google AdSense Params (Empty placeholder)
    [params.adsense]
        client = "" # Add your pub-XXXXXXXXXXXXXXXX ID here when ready
